### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by mgrandau** [Microsoft/workbooks#494]
### Steps to Reproduce

1. New workfow
2. Try to Add a Nuget from VSTS
3. 

### Expected Behavior
It works when I hit nuget.org. So I can bring in nugets for use with my workbook.

### Actual Behavior
It doesn't work work when attempting to load a nuget from my VSTS Packages. I can bring packages into my Visual Studio

[Error][00:00:52.5704437] PackageManagerWindow (OnSearchTextChanged): exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://tfsmadison.pkgs.visualstudio.com/_packaging/Dev_Architecture/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.PackageSearchResourceV3Provider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Interactive.NuGet.PackageManagerViewModel.<SearchForPackagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Interactive.Client.Windows.Views.PackageManagerWindow.<OnSearchTextChanged>d__38.MoveNext() @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client.Windows\Views\PackageManagerWindow.xaml.cs:128

### Environment
Windows 10.

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.4.3 |
| Git Branch | 1.4-release |
| Git Hash | db27525 |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component | Value |
| :- | :- |
| Windows | Microsoft Windows NT 10.0.15063.0 (64-bit) |
| CPU Cores | 8 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Xamarin Simulator | 1010209018 |

#### VisualStudio.15.Release Components
| Component | Version |
| :- | :- |
| Visual Studio Professional 2017 | 15.8.4+28010.2026 |
| Xamarin iOS | 11.14.0-13 |
| Xamarin Android | 9.0.0-19 |

### Log File

[Xamarin Workbooks 2018-09-18.log](https://github.com/Microsoft/workbooks/files/2393275/Xamarin.Workbooks.2018-09-18.log)

**Comment by sandyarmstrong** [comment]
I believe Visual Studio is using some sort of VSTS authentication plugin that lets this work more automatically from the IDE.

For Workbooks, you need to make sure your `NuGet.Config` file (located at `%appdata%\NuGet\NuGet.Config`) lists the feed and includes authentication information. These instructions for using VSTS feeds with `dotnet` are also applicable to Workbooks: https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=vsts .

I'm guessing your `NuGet.Config` file already lists the repos, but lacks the VSTS PAT credentials.
